name: lovenote
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_screenutil: ^5.0.0  
  cupertino_icons: ^1.0.2
  dio: ^3.0.9
  # drag_container: ^1.0.1
  sliding_up_panel: ^0.3.6
  liquid_swipe: ^1.3.0
  image_picker: ^0.6.1+8
  socket_io_client: ^0.9.12
  flutter_neumorphic: ^3.1.0  
  # permission_handler: ^5.0.1+1
  animations: ^1.1.1
   #偏好设置
  shared_preferences: ^2.0.5
   # WebView
  webview_flutter: ^2.0.4
   #App版本信息
  package_info: ^0.4.3+2
  permission_handler: ^6.1.3
  fluttertoast: ^8.0.6
  video_player: ^2.1.1  
  path_provider: ^2.0.1
  shake_animation_widget: ^2.1.2
  #抖动组件
  flukit: ^1.0.2
  nine_grid_view: ^2.0.0
  azlistview: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/hbg.jpg
    - assets/images/avatar.jpg
    - assets/images/avatar2.jpg
    - assets/images/mesagebg.jpg
    - assets/images/message.jpg
    - assets/images/message1.png
    - assets/images/message2.jpg
    - assets/images/user_bg.png

    
    - assets/icon/diary.png
    - assets/icon/more.png 
    - assets/icon/photo.png
    - assets/icon/sing.png

    - assets/icon/user_addtime.png
    - assets/icon/user_game.png
    - assets/icon/user_image.png
    - assets/icon/user_theme.png
    - assets/icon/app_icon.png
    - assets/icon/wchat.png
    - assets/icon/qq.png
    - assets/icon/login_bg.png
    - assets/icon/sex_0.png
    - assets/icon/sex_1.png


    - assets/icon/tab/activity.png
    - assets/icon/tab/comm.png
    - assets/icon/tab/home.png
    - assets/icon/tab/me.png
    - assets/icon/tab/message.png
    - assets/icon/tab/pair.png
    - assets/icon/tab/activity.png
    - assets/icon/tab/activity_check.png
    - assets/icon/tab/comm_check.png
    - assets/icon/tab/home_check.png
    - assets/icon/tab/me_check.png
    - assets/icon/tab/message_check.png
    - assets/icon/tab/pair_check.png
    - assets/icon/tab/activity_check.png


    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/banner4.jpg
    - assets/images/banner5.jpg  
    - assets/images/welcome_bg.gif 
    - assets/images/splansh_bg.png 

    - assets/images/ali_connors.png    
    - assets/images/ali_landscape.png    
    - assets/images/ali.png    
    - assets/images/avatar.png  
    - assets/images/cat.png    
    # - assets/video/     
    #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
